application: piskel-app
version: beta
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?(\.git/.*)$

handlers:
- url: /favicon\.ico
  static_files: static/resources/favicon.ico
  upload: static/resources/favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /google392c8e9117089539\.html
  static_files: static/google392c8e9117089539.html
  upload: static/google392c8e9117089539\.html

- url: /static/resources/(.*\.svg)
  static_files: static/resources/\1
  upload: static/resources/(.*\.svg)
  mime_type: image/svg+xml

- url: /static/resources/(.*\.eot)
  static_files: static/resources/\1
  upload: static/resources/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /static/resources/(.*\.ttf)
  static_files: static/resources/\1
  upload: static/resources/(.*\.ttf)
  mime_type: application/octet-stream

- url: /static/resources/(.*\.woff)
  static_files: static/resources/\1
  upload: static/resources/(.*\.woff)
  mime_type: application/x-woff

- url: /static/resources/(.*\.png)
  static_files: static/resources/\1
  upload: static/resources/(.*\.png)
  mime_type: image/png

- url: /static
  static_dir: static

- url: /p/(.*\.svg)
  static_files: static/editor/\1
  upload: static/editor/(.*\.svg)
  mime_type: image/svg+xml

- url: /p/(.*\.eot)
  static_files: static/editor/\1
  upload: static/editor/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /p/(.*\.ttf)
  static_files: static/editor/\1
  upload: static/editor/(.*\.ttf)
  mime_type: application/octet-stream

- url: /p/(.*\.woff)
  static_files: static/editor/\1
  upload: static/editor/(.*\.woff)
  mime_type: application/x-woff

- url: /p/(.*\.png)
  static_files: static/editor/\1
  upload: static/editor/(.*\.png)
  mime_type: image/png

- url: /p/(.*\.(?:css|js|gif))
  static_files: static/editor/\1
  upload: static/editor/(.*\.(css|js|gif))

- url: /p/templates(?:.*?)/(.*\.html)
  static_files: static/editor/templates/\1
  upload: static/editor/templates/(.*\.html)

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: "2.6"

- name: lxml
  version: "latest"